//
//  MBCMobage.h
//  mobage-ndk
//
//  Copyright (c) 2012, DeNA Co., Ltd. All rights reserved
//
//

#ifndef MBCMOBAGE_H_
#define MBCMOBAGE_H_

#include "MBCStandardTypes.h"
#include "MBCError.h"

#ifdef __cplusplus
extern "C" {
#endif

#pragma mark Enums / Bitfields
/**
 * Enumeration of Mobage server environments that an app can use.
 * @region Common
 */
typedef enum {
	/**
	 *
	 * Production environment.
	 * Use this environment when you are ready to submit your app to Mobage for publication.
	 */
	MBCServerEnvironmentProduction = 0, 
	/**
	 *
	 * Sandbox environment.
	 * Use this environment for testing your app.
	 */
	MBCServerEnvironmentSandbox = 1
} MBCServerEnvironment;
#define IsMBCServerEnvironment(intFlag) (!((intFlag < 0) || (intFlag > 1)))

	
	#pragma mark - Method Callbacks!
	/**
	 * MBCMobage_attemptToReestablishSessionCallback
	 * @description 	 * Callback for reestablishing a session for the most recent user.
	 * @cb-param MBCSimpleAPIStatus status Information about the result of the request.			
	 * @cb-param MBCError * error Information about the error, or <c>null</c> if there was not an error.			AUTORELEASED
	 * @cb-param bool sessionEstablished Set to <c>true</c> if the session was reestablished or <c>false</c> if it was not reestablished.			
	 */
	typedef void (*MBCMobage_attemptToReestablishSessionCallback)(
				MBCSimpleAPIStatus status,
				/*AUTORELEASED*/ MBCError * error,
				bool sessionEstablished,
				
				void * context
																);
	
	#pragma mark - Static Methods
	/**
	 * MBCMobage_initializeMobageWithStandardParameters
	 * @function
	 * @public
	 * @description 	 * Initialize the Mobage service, and report a Mobage analytics event indicating that the app has started.
	 * Call this method immediately after your app starts.
	 * <p>
	 * <strong>Important</strong>: Call this method only once.
	 *
	 * @param MBCServerEnvironment  serverEnvironment Indicates whether to connect to Mobage's sandbox or production environment. Contains an enumerated value of Mobage::ServerEnvironment. <strong>Important</strong>: Before you submit your app to Mobage for review, you must change this value to refer to Mobage's production environment.			
	 * @param const char *  appId The app ID, also known as the "app key." Generated by the <a href="https://developer.mobage.com/">Mobage Developer Portal</a>.			AUTORELEASED
	 * @param const char *  appVersion The app version.			AUTORELEASED
	 * @param const char *  consumerKey The app's OAuth key for accessing the Mobage service. Generated by the <a href="https://developer.mobage.com/">Mobage Developer Portal</a>.			AUTORELEASED
	 * @param const char *  consumerSecret The app's OAuth secret for accessing the Mobage service. Generated by the <a href="https://developer.mobage.com/">Mobage Developer Portal</a>.			AUTORELEASED
	 * <br/>
	 */
	void MBCMobage_initializeMobageWithStandardParameters(
										MBCServerEnvironment  serverEnvironment,
										const char *  appId,
										const char *  appVersion,
										const char *  consumerKey,
										const char *  consumerSecret,
										
										void * context	//Arbitrary Context Object, which will be passed back to callbacks
						   );


#ifdef __cplusplus
}
#endif

#endif /* MBCMOBAGE_H_ */

